### ISSUE TITLE
Problem with Servo mode while using Extended Analog messages

### ISSUE THREAD

**Issue by OlivieriIan** [firmata/firmata_test#6]
Hi

I had a problem with the angle 128 for the extended analog message (pins > 15)

What I did was:
I changed pin's 16 mode to Servo. While sniffing the port with "Device Monitoring Studio" I gently moved the slider to get all the values in the range. I did it several times to verify that it was no coincidence, and the result obtained was consistent. 

Values obtained can be seen in the following file:

[servo message analysis.txt](https://github.com/firmata/firmata_test/files/139367/servo.message.analysis.txt)

specifically, what I got while moving from 127 to 128 was:
F0 6F 10 7F F7 (message for 127)
F0 6F 10 00 F7 (message for 128) <-- this should be F0 6F 10 00 01 F7

Snap solves this problem by sending a fixed lenght message for each value:
F0 6F 10 00 00 F7 (message for 0)
F0 6F 10 7F 00 F7 (message for 127)
F0 6F 10 00 01 F7 (message for 128)

**Comment by soundanalogous** [comment]
Does it only happen with 128 or are all values > 127 truncated at 127?

**Comment by OlivieriIan** [comment]
only with 128, although the value that follows it is 130, not 129, so i don't really know if 129 has the same issue

**Comment by soundanalogous** [comment]
I suspect the issue is [here](https://github.com/firmata/firmata_test/blob/master/firmata_test.cpp#L335-L338).
Should be `if (val >= 0x00000080) buf[len++] = (val >> 7) & 0x7F;` etc rather than `if (val > 0x0x00000080...`

**Comment by OlivieriIan** [comment]
makes sense. But how do I change the program to test if that's the problem? Sorry for the newbie question, but I really don't know

**Comment by soundanalogous** [comment]
No one is really maintaining the firmata_test application anymore. However I'll see what I can do. It may not get to it for a couple of weeks because I'll be traveling.

**Comment by soundanalogous** [comment]
What is it exactly that you need from firmata_test? It would probably be easier for me to write an entirely new cross-platform application in Java or JavaScript (using something like NW.js) than it would be for me to try to maintain the firmata_test application.

**Comment by OlivieriIan** [comment]
No problem, I just wanted to let you know about the issue, just that. I was playing with an arduino and the app, discovered it and felt like telling you guys about it.

Thanks for your help man :)
